### ISSUE TITLE
axfrdns exits after 60 seconds unable to read from the network

### ISSUE THREAD

**Issue by tjconnelly** [pjps/ndjbdns#26]
i'm trying to get axfrdns running on centos7 using systemd. at first, i couldn't understand why axfrdns@.service was set as a template since there don't appear to be any tokens to replace in the config. after several different tries and a lot of reading i tried to isolate the problem to axfrdns.

at this point i've read about a third of the code and i don't know C particularly well. however, even when testing from the command line, axfrdns -D gives the following output (to /var/log/axfrdns.log):

```
axfrdns: GID: 2
axfrdns: ROOT: /etc/ndjbdns
axfrdns: DEBUG_LEVEL: 1
axfrdns: DEBUG_LEVEL set to `1'
axfrdns: AXFR set to `(null)'
axfrdns: TCPREMOTEIP set to `(null)'
axfrdns: TCPREMOTEPORT set to `(null)'
axfrdns: root & working directory changed to `/etc/ndjbdns'
axfrdns: root privileges dropped, user-id set to `2'
axfrdns: could not read from the network: Connection timed out
```

about 60 seconds elapses between root privs dropped and could not read from the network; on the command line, no output. i've disabled firewalls, i've tried running with and without -D and it only seems to affect where the errors are logging; i also tried checking during the interval, and i get nowhere.

it seems the error is generated by netread around line 564 of axfrdns:

```
for (;;)
    {
        netread (tcpheader, 2);
        uint16_unpack_big (tcpheader, &len);
        if (len > 512)
            errx (-1, "excessively large request");
        netread (buf, len);
```

i'm confused in that it doesn't seem like it should be triggered until the server receives a request, but again this is not my area of expertise.

i've put about three hours into it so far; i'm now willing to advance this may be a bug and not my own ignorance. if i'm wrong, i'd love to hear about it, along with some explicit instructions for getting this working under systemd.

meanwhile tinydns is running wonderfully, and i am very grateful you've taken the time to port this. i would feel very strange to go back to running BIND after all these years.

thank you -TJ

**Comment by pjps** [comment]
Hello TJ,

Thank you so much for reporting this issue and for providing the details. I'll debug this further over the weekend and will get back to you.

Thank you.

**Comment by tjconnelly** [comment]
much appreciated! i have to confess since putting this time in i find myself in need of an AAAA record, which doesn't appear to be implemented. unfortunately i'm going to have to switch software in the near term, but i will stay tuned for future updates. thanks!

**Comment by msimerson** [comment]
FWIW, djbdns supports AAAA just fine via generic records. I have examples for generating the proper tinydns data format for all the non-native record types in [this perl export class](https://github.com/msimerson/NicTool/blob/master/server/lib/NicToolServer/Export/tinydns.pm).

**Comment by tjconnelly** [comment]
seems dead, yrstruly no longer running DNS services. closing, thx for your time.
